apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: benddeploy
  labels:
    app: benddeploy
  namespace: benddeploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: benddeploy
subjects:
  - kind: ServiceAccount
    name: benddeploy
    namespace: benddeploy
