apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benddeploy
  namespace: benddeploy
  labels:
    app: benddeploy

rules:
  # Allow all actions on core API resources
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

  # Allow all actions on commonly used API groups
  - apiGroups: 
      - "apps"
      - "autoscaling"
      - "batch"
      - "extensions"
      - "policy"
      - "networking.k8s.io"
      - "rbac.authorization.k8s.io"
      - "storage.k8s.io"
      - "monitoring.coreos.com"
      - "scheduling.k8s.io"
    resources: ["*"]
    verbs: ["*"]

  # Allow specific actions on CustomResourceDefinitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
