apiVersion: v1
kind: ConfigMap
metadata:
  name: benddeploy-config
  namespace: benddeploy
data:
  config.json: |
    {
      "env": "test",
      "namespace": "benddeploy",
      "imageRegistry": "",
      "secretKey": "",
      "lokiHost": "",
      "grafanaEndpoint": "http://grafana.monitoring.svc.cluster.local:80",
      "promEndpoint": "thanos-query.monitoring.svc.cluster.local:9090",
      "logCollectorEndpoint": "http://warehouse-log-collector.logging.svc.cluster.local:4318",
      "salt": "salt",
      "jwt": {
        "kind": "static",
        "static": {
          "signingKey": "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIN2zd9w6nMcFpP0FuUb3413RSgo92nhtGYlXSBfgQD9yoAoGCCqGSM49\nAwEHoUQDQgAEJI4I7jG0eVUMTo8TkrOso1VTWBddEaUD2UI7efrYzmI2zFocd7Ga\nfLbl54WFHeJ75ur0ED8EUf7QPEmgkr5QHQ==\n-----END EC PRIVATE KEY-----",
          "pubKey": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJI4I7jG0eVUMTo8TkrOso1VTWBdd\nEaUD2UI7efrYzmI2zFocd7GafLbl54WFHeJ75ur0ED8EUf7QPEmgkr5QHQ==\n-----END PUBLIC KEY-----"
        }
      },
      "db": {
        "postgresDSN": "postgres://postgres:postgres@pg-benddeploy.benddeploy.svc.cluster.local:5432/default?sslmode=disable"
      },
      "adminUsers": [
        "databend",
        "admin"
      ],
      "jwtKeyFile": "http://benddeploy-service.benddeploy.svc.cluster.local:8080/.well-known/jwks.json",
      "oidcProvider": "https://oidc.eks.us-east-2.amazonaws.com/id/120A6F5E89F8F14E7A1E5E15FE48196D/keys"
    }