apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  SecretKey: N2U1ZDMzYTI3ZTVmNGY2NzFmZThmNWE0N2UxZmU3NjI=
  User: ZGF0YWJlbmQ=
  Password: MDY2OTBiMTdkOTcyNzE0OWRmYWU5YzJmZGRhYWM2MGI=