apiVersion: v1
kind: Service
metadata:
  name: benddeploy-service
  labels:
    app: benddeploy
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: benddeploy
